export const components = {
  accordion: {
    surfaceAccordionBgtrueDefault: '#fafafa',
    surfaceAccordionBgtrueHover: '#f3f3f5',
    surfaceAccordionBgtrueDisabled: '#fafafa',
    surfaceAccordionBgfalseDefault: '#ffffff00',
    surfaceAccordionBgfalseHover: '#f3f3f5',
    surfaceAccordionBgfalseDisabled: '#ffffff00',
    contentAccordionHeadingDefault: '#131313',
    contentAccordionHeadingDisabled: '#a3a3a3',
    contentAccordionDefault: '#292929',
    contentAccordionDisabled: '#a3a3a3',
    strokeAccordion: '#dedede',
    shapeAccordion: '0px',
  },
  avatar: {
    letter: {
      surfaceAvatarLetterDefault: '#000000',
      surfaceAvatarLetterHover: '#454545',
      surfaceAvatarLetterActive: '#454545',
      surfaceAvatarLetterDisabled: '#dedede',
      contentAvatarLetterDefault: '#ffffff',
      contentAvatarLetterHover: '#ffffff',
      contentAvatarLetterActive: '#ffffff',
      contentAvatarLetterDisabled: '#ffffff',
      strokeAvatarLetter: '#ffffff',
      shapeAvatarLetter: '100px',
    },
    collapsed: {
      surfaceAvatarCollapsedDefault: '#ffffff',
      surfaceAvatarCollapsedHover: '#dedede',
      surfaceAvatarCollapsedActive: '#dedede',
      surfaceAvatarCollapsedDisabled: '#ffffff',
      contentAvatarCollapsedDefault: '#454545',
      contentAvatarCollapsedHover: '#454545',
      contentAvatarCollapsedActive: '#454545',
      contentAvatarCollapsedDisabled: '#dedede',
      strokeAvatarCollapsed: '#ffffff',
      shapeAvatarCollapsed: '100px',
    },
    thumbnail: {
      surfaceAvatarThumbnailDefault: '#000000',
      surfaceAvatarThumbnailHover: '#454545',
      surfaceAvatarThumbnailActive: '#454545',
      surfaceAvatarThumbnailDisabled: '#dedede',
      contentAvatarThumbnailDefault: '#ffffff',
      contentAvatarThumbnailHover: '#ffffff',
      contentAvatarThumbnailActive: '#ffffff',
      contentAvatarThumbnailDisabled: '#ffffff',
      borderAvatarThumbnail: '#ffffff',
      shapeAvatarThumbnail: '100px',
    },
  },
  backdrop: {
    surfaceBackdropDark: '#131313',
    surfaceBackdropLight: '#131313',
    opacityBackdropDark: '85',
    opacityBackdropLight: '20',
  },
  badge: {
    surfaceBadgePrimary: '#00677f',
    surfaceBadgeSuccess: '#6ea046',
    surfaceBadgeWarning: '#e69123',
    surfaceBadgeError: '#a00000',
    contentBadge: '#ffffff',
    strokeBadge: '#ffffff',
    shapeBadge: '100px',
  },
  button: {
    primary: {
      solid: {
        surfaceButtonPrimarySolidDefault: '#000000',
        surfaceButtonPrimarySolidHover: '#454545',
        surfaceButtonPrimarySolidFocus: '#454545',
        surfaceButtonPrimarySolidActive: '#454545',
        surfaceButtonPrimarySolidDisabled: '#dedede',
        surfaceButtonPrimarySolidLoading: '#dedede',
        contentButtonPrimarySolidDefault: '#ffffff',
        contentButtonPrimarySolidHover: '#ffffff',
        contentButtonPrimarySolidFocus: '#ffffff',
        contentButtonPrimarySolidActive: '#ffffff',
        contentButtonPrimarySolidDisabled: '#ffffff',
        contentButtonPrimarySolidLoading: '#ffffff',
        shapeButtonPrimarySolid: '0px',
      },
      outlined: {
        surfaceButtonPrimaryOutlinedDefault: '#ffffff00',
        surfaceButtonPrimaryOutlinedHover: '#dedede',
        surfaceButtonPrimaryOutlinedFocus: '#dedede',
        surfaceButtonPrimaryOutlinedActive: '#dedede',
        surfaceButtonPrimaryOutlinedDisabled: '#ffffff00',
        surfaceButtonPrimaryOutlinedLoading: '#ffffff00',
        contentButtonPrimaryOutlinedDefault: '#000000',
        contentButtonPrimaryOutlinedHover: '#ffffff',
        contentButtonPrimaryOutlinedFocus: '#000000',
        contentButtonPrimaryOutlinedActive: '#000000',
        contentButtonPrimaryOutlinedDisabled: '#dedede',
        contentButtonPrimaryOutlinedLoading: '#dedede',
        strokeButtonPrimaryOutlinedDefault: '#000000',
        strokeButtonPrimaryOutlinedHover: '#000000',
        strokeButtonPrimaryOutlinedFocus: '#000000',
        strokeButtonPrimaryOutlinedActive: '#000000',
        borderButtonPrimaryOutlinedDisabled: '#dedede',
        borderButtonPrimaryOutlinedLoading: '#dedede',
        shapeButtonPrimaryOutlined: '0px',
      },
      text: {
        surfaceButtonPrimaryTextPositiveDefault: '#ffffff00',
        surfaceButtonPrimaryTextPositiveHover: '#dedede',
        surfaceButtonPrimaryTextPositiveFocus: '#dedede',
        surfaceButtonPrimaryTextPositiveActive: '#dedede',
        surfaceButtonPrimaryTextPositiveDisabled: '#ffffff00',
        surfaceButtonPrimaryTextPositiveLoading: '#ffffff00',
        contentButtonPrimaryTextPositiveDefault: '#000000',
        contentButtonPrimaryTextPositiveHover: '#000000',
        contentButtonPrimaryTextPositiveFocus: '#000000',
        contentButtonPrimaryTextPositiveActive: '#000000',
        contentButtonPrimaryTextPositiveDisabled: '#dedede',
        contentButtonPrimaryTextPositiveLoading: '#dedede',
        shapeButtonPrimaryText: '0px',
      },
    },
    secondary: {
      solid: {
        surfaceButtonSecondarySolidDefault: '#454545',
        surfaceButtonSecondarySolidHover: '#131313',
        surfaceButtonSecondarySolidFocus: '#131313',
        surfaceButtonSecondarySolidActive: '#131313',
        surfaceButtonSecondarySolidDisabled: '#c1c1c1',
        surfaceButtonSecondarySolidLoading: '#c1c1c1',
        contentButtonSecondarySolidDefault: '#ffffff',
        contentButtonSecondarySolidHover: '#ffffff',
        contentButtonSecondarySolidFocus: '#ffffff',
        contentButtonSecondarySolidActive: '#ffffff',
        contentButtonSecondarySolidDisabled: '#ffffff',
        contentButtonSecondarySolidLoading: '#ffffff',
        shapeButtonSecondarySolid: '0px',
      },
      outlined: {
        surfaceButtonSecondaryOutlinedDefault: '#ffffff00',
        surfaceButtonSecondaryOutlinedHover: '#c1c1c1',
        surfaceButtonSecondaryOutlinedFocus: '#c1c1c1',
        surfaceButtonSecondaryOutlinedActive: '#c1c1c1',
        surfaceButtonSecondaryOutlinedDisabled: '#ffffff00',
        surfaceButtonSecondaryOutlinedLoading: '#ffffff00',
        contentButtonSecondaryOutlinedDefault: '#454545',
        contentButtonSecondaryOutlinedHover: '#454545',
        contentButtonSecondaryOutlinedFocus: '#454545',
        contentButtonSecondaryOutlinedActive: '#454545',
        contentButtonSecondaryOutlinedDisabled: '#c1c1c1',
        contentButtonSecondaryOutlinedLoading: '#c1c1c1',
        strokeButtonSecondaryOutlinedDefault: '#454545',
        strokeButtonSecondaryOutlinedHover: '#454545',
        strokeButtonSecondaryOutlinedFocus: '#454545',
        strokeButtonSecondaryOutlinedActive: '#454545',
        borderButtonSecondaryOutlinedDisabled: '#c1c1c1',
        borderButtonSecondaryOutlinedLoading: '#c1c1c1',
        shapeButtonSecondaryOutlined: '0px',
      },
      text: {
        surfaceButtonSecondaryTextDefault: '#ffffff00',
        surfaceButtonSecondaryTextHover: '#c1c1c1',
        surfaceButtonSecondaryTextFocus: '#c1c1c1',
        surfaceButtonSecondaryTextActive: '#c1c1c1',
        surfaceButtonSecondaryTextDisabled: '#ffffff00',
        surfaceButtonSecondaryTextLoading: '#ffffff00',
        contentButtonSecondaryTextDefault: '#454545',
        contentButtonSecondaryTextHover: '#454545',
        contentButtonSecondaryTextFocus: '#454545',
        contentButtonSecondaryTextActive: '#454545',
        contentButtonSecondaryTextDisabled: '#c1c1c1',
        contentButtonSecondaryTextLoading: '#c1c1c1',
        shapeButtonSecondaryText: '0px',
      },
    },
    destructive: {
      solid: {
        surfaceButtonDestructiveSolidDefault: '#a00000',
        surfaceButtonDestructiveSolidHover: '#6d0000',
        surfaceButtonDestructiveSolidFocus: '#6d0000',
        surfaceButtonDestructiveSolidActive: '#6d0000',
        surfaceButtonDestructiveSolidDisabled: '#ffcbc0',
        surfaceButtonDestructiveSolidLoading: '#ffcbc0',
        contentButtonDestructiveSolidDefault: '#ffffff',
        contentButtonDestructiveSolidHover: '#ffffff',
        contentButtonDestructiveSolidFocus: '#ffffff',
        contentButtonDestructiveSolidActive: '#ffffff',
        contentButtonDestructiveSolidDisabled: '#ffffff',
        contentButtonDestructiveSolidLoading: '#ffffff',
        shapeButtonSecondarySolid: '0px',
      },
      outlined: {
        surfaceButtonDestructiveOutlinedDefault: '#ffffff00',
        surfaceButtonDestructiveOutlinedHover: '#ffcbc0',
        surfaceButtonDestructiveOutlinedFocus: '#ffcbc0',
        surfaceButtonDestructiveOutlinedActive: '#ffcbc0',
        surfaceButtonDestructiveOutlinedDisabled: '#ffffff00',
        surfaceButtonDestructiveOutlinedLoading: '#ffffff00',
        contentButtonDestructiveOutlinedDefault: '#a00000',
        contentButtonDestructiveOutlinedHover: '#a00000',
        contentButtonDestructiveOutlinedFocus: '#a00000',
        contentButtonDestructiveOutlinedActive: '#a00000',
        contentButtonDestructiveOutlinedDisabled: '#ffcbc0',
        contentButtonDestructiveOutlinedLoading: '#ffcbc0',
        strokeButtonDestructiveOutlinedDefault: '#a00000',
        strokeButtonDestructiveOutlinedHover: '#a00000',
        strokeButtonDestructiveOutlinedFocus: '#a00000',
        strokeButtonDestructiveOutlinedActive: '#a00000',
        strokeButtonDestructiveOutlinedDisabled: '#ffcbc0',
        strokeButtonDestructiveOutlinedLoading: '#ffcbc0',
        shapeButtonSecondaryOutlined: '0px',
      },
      text: {
        surfaceButtonDestructiveTextDefault: '#ffffff00',
        surfaceButtonDestructiveTextHover: '#ffcbc0',
        surfaceButtonDestructiveTextFocus: '#ffcbc0',
        surfaceButtonDestructiveTextActive: '#ffcbc0',
        surfaceButtonDestructiveTextDisabled: '#ffffff00',
        surfaceButtonDestructiveTextLoading: '#ffffff00',
        contentButtonDestructiveTextDefault: '#a00000',
        contentButtonDestructiveTextHover: '#a00000',
        contentButtonDestructiveTextFocus: '#a00000',
        contentButtonDestructiveTextActive: '#a00000',
        contentButtonDestructiveTextDisabled: '#ffcbc0',
        contentButtonDestructiveTextLoading: '#ffcbc0',
        shapeButtonDestructiveText: '0px',
      },
    },
    contrast: {
      solid: {
        surfaceButtonContrastSolidDefault: '#ffffff',
        surfaceButtonContrastSolidHover: '#c1c1c1',
        surfaceButtonContrastSolidFocus: '#c1c1c1',
        surfaceButtonContrastSolidActive: '#c1c1c1',
        surfaceButtonContrastSolidDisabled: '#ffffff',
        surfaceButtonContrastSolidLoading: '#ffffff',
        contentButtonContrastSolidDefault: '#131313',
        contentButtonContrastSolidHover: '#131313',
        contentButtonContrastSolidFocus: '#131313',
        contentButtonContrastSolidActive: '#131313',
        contentButtonContrastSolidDisabled: '#838383',
        contentButtonContrastSolidLoading: '#838383',
        shapeButtonContrastSolid: '0px',
      },
      outlined: {
        surfaceButtonContrastOutlinedDefault: '#ffffff00',
        surfaceButtonContrastOutlinedHover: '#ffffff',
        surfaceButtonContrastOutlinedFocus: '#ffffff',
        surfaceButtonContrastOutlinedActive: '#ffffff',
        surfaceButtonContrastOutlinedDisabled: '#ffffff00',
        surfaceButtonContrastOutlinedLoading: '#ffffff00',
        contentButtonContrastOutlinedDefault: '#ffffff',
        contentButtonContrastOutlinedHover: '#131313',
        contentButtonContrastOutlinedFocus: '#131313',
        contentButtonContrastOutlinedActive: '#131313',
        contentButtonContrastOutlinedDisabled: '#838383',
        contentButtonContrastOutlinedLoading: '#838383',
        strokeButtonContrastOutlinedDefault: '#ffffff',
        strokeButtonContrastOutlinedHover: '#ffffff',
        strokeButtonContrastOutlinedFocus: '#ffffff',
        strokeButtonContrastOutlinedActive: '#ffffff',
        strokeButtonContrastOutlinedDisabled: '#838383',
        strokeButtonContrastOutlinedLoading: '#838383',
        shapeButtonOutlinedNegative: '0px',
      },
      text: {
        surfaceButtonPrimaryTextNegativeDefault: '#ffffff00',
        surfaceButtonPrimaryTextNegativeHover: '#c1c1c1',
        surfaceButtonPrimaryTextNegativeFocus: '#c1c1c1',
        surfaceButtonPrimaryTextNegativeActive: '#c1c1c1',
        surfaceButtonPrimaryTextNegativeDisabled: '#ffffff00',
        surfaceButtonPrimaryTextNegativeLoading: '#ffffff00',
        contentButtonPrimaryTextNegativeDefault: '#ffffff',
        contentButtonPrimaryTextNegativeHover: '#131313',
        contentButtonPrimaryTextNegativeFocus: '#131313',
        contentButtonPrimaryTextNegativeActive: '#131313',
        contentButtonPrimaryTextNegativeDisabled: '#838383',
        contentButtonPrimaryTextNegativeLoading: '#838383',
        shapeButtonPrimaryText: '0px',
      },
    },
  },
  breadcrumb: {
    contentBreadcrumbCurrentDefault: '#636363',
    contentBreadcrumbCurrentHover: '#ffffff00',
    contentBreadcrumbPreviousDefault: '#00677f',
    contentBreadcrumbPreviousHover: '#003041',
    contentBreadcrumbSlash: '#292929',
    contentBreadcrumbIcon: '#292929',
  },
  card: {
    surfaceCardDefault: '#ffffff',
    surfaceCardHover: '#dedede',
    surfaceCardSelected: '#dedede',
    contentCardTitle: '#131313',
    contentCardDescription: '#292929',
    strokeCard: '#000000',
    shapeCard: '0px',
  },
  checkbox: {
    checkedTrue: {
      surfaceCheckboxCheckedEnabled: '#00677f',
      surfaceCheckboxCheckedDisabled: '#cce3eb',
      surfaceCheckboxCheckedError: '#a00000',
    },
    checkedFalse: {
      surfaceCheckboxUncheckedDefault: '#ffffff',
      surfaceCheckboxUncheckedHover: '#cce3eb',
      surfaceCheckboxUncheckedDisabled: '#fafafa',
      strokeCheckboxUncheckedDefault: '#dedede',
      strokeCheckboxUncheckedHover: '#00677f',
      strokeCheckboxUncheckedDisabled: '#dedede',
      strokeCheckboxUncheckedError: '#a00000',
    },
    contentCheckboxDefault: '#292929',
    contentCheckboxContrast: '#ffffff',
    contentCheckboxDisabled: '#636363',
    shapeCheckbox: '0px',
    checkedIndeterminate: {
      surfaceCheckboxIndeterminateEnabled: '#454545',
      surfaceCheckboxIndeterminateDisabled: '#c1c1c1',
    },
  },
  container: {
    surfaceContainerDefault: '#ffffff',
    surfaceContainerContrast: '#f3f3f5',
    surfaceContainerNull: '#ffffff00',
    strokeContainerTrue: '#dedede',
    strokeContainerFalse: '#ffffff00',
    shapeContainer: '0px',
  },
  datepicker: {
    surfaceDatepickerDefault: '#ffffff',
    surfaceDatepickerHover: '#cce3eb',
    surfaceDatepickerSelected: '#000000',
    contentDatepickerDark: '#131313',
    contentDatepickerDefault: '#292929',
    contentDatepickerHover: '#ffffff',
    contentDatepickerDisabled: '#a3a3a3',
    strokeDatepicker: '#00677f',
    shapeDatepicker: '0px',
  },
  definitionList: {
    surfaceDefinitionListDefault: '#fafafa',
    surfaceDefinitionListNull: '#ffffff00',
    contentDefinitionListDefault: '#292929',
    contentDefinitionListLight: '#636363',
    contentDefinitionListContrast: '#131313',
    strokeDefinitionListTrue: '#dedede',
    strokeDefinitionListFalse: '#ffffff00',
    shapeDefinitionList: '0px',
  },
  drawer: {
    surfaceDrawerDefault: '#ffffff',
    contentDrawerHeading: '#131313',
    contentDrawer: '#636363',
    shapeDrawer: '0px',
  },
  emptyState: {
    surfaceEmptyStateDefault: '#f3f3f5',
    surfaceEmptyStateLight: '#fafafa',
    surfaceEmptyStateContrast: '#ffffff',
    surfaceEmptyStateNull: '#ffffff00',
    contentEmptyStateTitle: '#131313',
    contentEmptyStateDescription: '#292929',
    strokeEmptyState: '#dedede',
    contentEmptyStateShape: '0px',
  },
  footer: {
    surfaceFooter: '#f3f3f5',
    contentFooterDefault: '#292929',
    contentFooterHover: '#000000',
    shapeFooter: '0px',
  },
  header: {
    surfaceHeader: '#ffffff',
    surfaceSubheader: '#ffffff',
    contentHeaderMain: '#000000',
    contentHeaderSecondary: '#636363',
    contentLinkDefault: '#131313',
    contentLinkHover: '#636363',
    contentLinkActive: '#131313',
    shapeHeader: '0px',
  },
  icons: {
    contentIconsDefault: '#292929',
    contentIconsHover: '#00677f',
    contentIconsActive: '#00677f',
    contentIconsDisabled: '#a3a3a3',
    contentIconsContrastDefault: '#ffffff',
    contentIconsContrastHover: '#73aec2',
    contentIconsContrastActive: '#73aec2',
    contentIconsContrastDisabled: '#292929',
  },
  link: {
    contentLinkPrimaryDefault: '#000000',
    contentLinkPrimaryHover: '#000000',
    contentLinkPrimaryActive: '#454545',
    contentLinkPrimaryDisabled: '#dedede',
    contentLinkSecondaryDefault: '#454545',
    contentLinkSecondaryHover: '#454545',
    contentLinkSecondaryActive: '#131313',
    contentLinkSecondaryDisabled: '#c1c1c1',
  },
  loadingSpinner: {
    positive: {
      surfaceLoadingSpinnerPositive: '#dedede',
      contentLoadingSpinnerPositive: '#292929',
      strokeLoadingSpinnerPositive: '#000000',
    },
    negative: {
      surfaceLoadingSpinnerNegative: '#454545',
      contentLoadingSpinnerNegative: '#ffffff',
      strokeLoadingSpinnerNegative: '#ffffff',
    },
  },
  messages: {
    default: {
      surfaceMessagesDefault: '#fafafa',
      contentMessagesDefaultMgIcon: '#292929',
      contentMessagesDefaultTitle: '#131313',
      contentMessagesDefaultDescription: '#292929',
      contentMessagesDefaultCloseIcon: '#292929',
      contentMessagesDefaultActions: '#454545',
      strokeMessagesDefault: '#dedede',
      shapeMessagesDefault: '0px',
    },
    error: {
      surfaceMessagesError: '#ffcbc0',
      contentMessagesErrorMgIcon: '#a00000',
      contentMessagesErrorTitle: '#131313',
      contentMessagesErrorDescription: '#292929',
      contentMessagesErrorCloseIcon: '#292929',
      contentMessagesErrorActions: '#454545',
      strokeMessagesError: '#a00000',
      shapeMessagesError: '0px',
    },
    info: {
      surfaceMessagesInfo: '#e8f4ff',
      contentMessagesInfoMgIcon: '#008dfc',
      contentMessagesInfoTitle: '#131313',
      contentMessagesInfoDescription: '#292929',
      contentMessagesInfoCloseIcon: '#292929',
      contentMessagesInfoActions: '#454545',
      strokeMessagesInfo: '#008dfc',
      shapeMessagesInfo: '0px',
    },
    success: {
      surfaceMessagesSuccess: '#eff5eb',
      contentMessagesSuccessMgIcon: '#6ea046',
      contentMessagesSuccessTitle: '#131313',
      contentMessagesSuccessDescription: '#292929',
      contentMessagesSuccessCloseIcon: '#292929',
      contentMessagesSuccessActions: '#454545',
      strokeMessagesSuccess: '#6ea046',
      shapeMessagesSuccess: '0px',
    },
    warning: {
      surfaceMessagesWarning: '#fbf1e7',
      contentMessagesWarningMgIcon: '#e69123',
      contentMessagesWarningTitle: '#131313',
      contentMessagesWarningDescription: '#292929',
      contentMessagesWarningCloseIcon: '#292929',
      contentMessagesWarningActions: '#454545',
      strokeMessagesWarning: '#e69123',
      shapeMessagesWarning: '0px',
    },
  },
  modal: {
    surfaceModal: '#ffffff',
    surfaceModalFooterContrast: '#ffffff',
    surfaceModalFooterAlternative: '#f3f3f5',
    contentModalTitle: '#131313',
    contentModal: '#292929',
    strokeModal: '#dedede',
    shapeModal: '0px',
  },
  navigationMenu: {
    surfaceNavigationMenu: '#000000',
    contentNavigationMenuDefault: '#ffffff',
    contentNavigationMenuHover: '#a3a3a3',
    contentNavigationMenuActive: '#ffffff',
    strokeNavigationMenu: '#c1c1c1',
    contentNavigationMenuIcon: '#ffffff',
    shapeNavigationMenu: '0px',
  },
  numberField: {
    surfaceNumberFieldDefault: '#f3f3f5',
    surfaceNumberFieldLight: '#fafafa',
    surfaceNumberFieldContrast: '#ffffff',
    contentNumberFieldLabel: '#292929',
    contentNumberFieldLabelReadOnly: '#636363',
    contentNumberFieldLabelError: '#a00000',
    contentNumberFieldLabelDisabled: '#a3a3a3',
    contentNumberFieldLabelFloating: '#636363',
    contentNumberFieldLabelFloatingError: '#a00000',
    contentNumberFieldLabelFloatingDisabled: '#a3a3a3',
    contentNumberFieldPlaceholder: '#636363',
    contentNumberFieldPlaceholderDisabled: '#a3a3a3',
    contentNumberFieldText: '#292929',
    contentNumberFieldTextReadOnly: '#636363',
    contentNumberFieldTextDisabled: '#a3a3a3',
    contentNumberFielddInfo: '#636363',
    contentNumberFieldInfoError: '#a00000',
    contentNumberFieldInfoDisabled: '#a3a3a3',
    contentNumberFieldMandatory: '#a00000',
    contentNumberFieldMandatoryDisabled: '#a3a3a3',
    contentNumberFieldIcons: '#292929',
    contentNumberFieldIconsHover: '#131313',
    contentNumberFieldIconsReadOnly: '#636363',
    contentNumberFieldIconsError: '#a00000',
    contentNumberFieldIconsDisabled: '#a3a3a3',
    strokeNumberField: '#c1c1c1',
    strokeNumberFieldHover: '#131313',
    strokeNumberFieldError: '#a00000',
    strokeNumberFieldActive: '#131313',
    surfaceNumberFieldControlsDefault: '#ffffff00',
    surfaceNumberFieldControlsHover: '#dedede',
    surfaceNumberFieldControlsActive: '#dedede',
    surfaceNumberFieldControlsDisabled: '#ffffff00',
    contentNumberFieldControlsDefault: '#292929',
    contentNumberFieldControlsHover: '#292929',
    contentNumberFieldControlsActive: '#131313',
    contentNumberFieldControlsDisabled: '#a3a3a3',
    strokeNumberFieldControlsDefault: '#ffffff00',
    strokeNumberFieldControlsActive: '#131313',
    strokeNumberFieldControlsDisabled: '#ffffff00',
    shapeNumberField: '0px',
  },
  option: {
    surfaceOptionDefault: '#ffffff00',
    surfaceOptionHover: '#cce3eb',
    surfaceOptionSelected: '#ffffff00',
    surfaceOptionSelectedhovered: '#cce3eb',
    surfaceOptionDisabled: '#ffffff00',
    surfaceOptionSelecteddisabled: '#fafafa',
    surfaceOptionDividerDefault: '#ffffff00',
    surfaceOptionDividerDisabled: '#ffffff00',
    contentOptionDefault: '#292929',
    contentOptionHover: '#292929',
    contentOptionSelected: '#292929',
    contentOptionSelectedhovered: '#292929',
    contentOptionDisabled: '#a3a3a3',
    contentOptionSelecteddisabled: '#a3a3a3',
    contentOptionDividerDefault: '#131313',
    contentOptionDividerDisabled: '#a3a3a3',
    shapeOption: '0px',
  },
  pagination: {
    surfacePaginationItemDefault: '#ffffff00',
    surfacePaginationItemHover: '#cce3eb',
    surfacePaginationItemActive: '#000000',
    surfacePaginationItemDisabled: '#ffffff00',
    contentPaginationItemDefault: '#292929',
    contentPaginationItemHover: '#292929',
    contentPaginationItemActive: '#ffffff',
    contentPaginationItemDisabled: '#a3a3a3',
    contentPaginationTextBold: '#131313',
    contentPaginationTextRegular: '#292929',
    shapePaginationItem: '0px',
  },
  progressBar: {
    surfaceProgressBarBg: '#dedede',
    surfaceProgressBarBar: '#000000',
    contentProgressBarLabel: '#131313',
    contentProgressBar: '#131313',
    contentProgressBarInfo: '#636363',
    shapeProgressBar: '0px',
  },
  radioButton: {
    contentRadioButtonDefault: '#292929',
    contentRadioButtonContrast: '#ffffff',
    contentRadioButtonDisabled: '#636363',
    shapeRadioButton: '100px',
    selectedTrue: {
      surfaceRadioButtonSelectedDefault: '#00677f',
      surfaceRadioButtonSelectedCheckedDisabled: '#cce3eb',
      surfaceRadioButtonSelectedError: '#a00000',
    },
    selectedFalse: {
      surfaceRadioButtonUnselectedDefault: '#ffffff',
      surfaceRadioButtonUnselectedHover: '#cce3eb',
      surfaceRadioButtonUnselectedDisabled: '#fafafa',
      strokeRadioButtonUnselectedHover: '#00677f',
      strokeRadioButtonUnselectedDisabled: '#dedede',
      strokeRadioButtonUnselectedError: '#a00000',
      strokeRadioButtonUnselectedDefault: '#dedede',
    },
  },
  searchField: {
    surfaceSearchFieldDefault: '#f3f3f5',
    surfaceSearchFieldLight: '#fafafa',
    surfaceSearchFieldContrast: '#ffffff',
    contentSearchFieldLabel: '#292929',
    contentSearchFieldLabelDisabled: '#a3a3a3',
    contentSearchFieldLabelFloating: '#636363',
    contentSearchFieldLabelFloatingDisabled: '#a3a3a3',
    contentSearchFieldPlaceholder: '#636363',
    contentSearchFieldPlaceholderDisabled: '#a3a3a3',
    contentSearchFieldText: '#292929',
    contentSearchFieldTextDisabled: '#a3a3a3',
    contentSearchFieldInfo: '#636363',
    contentSearchFieldInfoDisabled: '#a3a3a3',
    contentSearchFieldMandatoryDisabled: '#a3a3a3',
    contentSearchFieldIcons: '#292929',
    contentSearchFieldIconsHover: '#131313',
    contentSearchFieldIconsDisabled: '#a3a3a3',
    strokeSearchField: '#c1c1c1',
    strokeSearchFieldHover: '#131313',
    strokeSearchFieldActive: '#131313',
    shapeSearField: '0px',
  },
  segmentedControl: {
    surfaceSegmentedControlDefault: '#ffffff',
    strokeSegmentedControl: '#c1c1c1',
    shapeSegmentedControl: '0px',
  },
  selectField: {
    surfaceSelectFieldDefault: '#f3f3f5',
    surfaceSelectFieldLight: '#fafafa',
    surfaceSelectFieldContrast: '#ffffff',
    contentSelectFieldLabel: '#292929',
    contentSelectFieldLabelError: '#a00000',
    contentSelectFieldLabelDisabled: '#a3a3a3',
    contentSelectFieldLabelFloating: '#636363',
    contentSelectFieldLabelFloatingError: '#a00000',
    contentSelectFieldLabelFloatingDisabled: '#a3a3a3',
    contentSelectFieldPlaceholder: '#636363',
    contentSelectFieldPlaceholderDisabled: '#a3a3a3',
    contentSelectFieldText: '#292929',
    contentSelectFieldTextDisabled: '#a3a3a3',
    contentSelectFieldInfo: '#636363',
    contentSelectFieldInfoError: '#a00000',
    contentSelectFieldInfoDisabled: '#a3a3a3',
    contentSelectFieldMandatory: '#a00000',
    contentSelectFieldMandatoryDisabled: '#a3a3a3',
    contentSelectFieldIcons: '#292929',
    contentSelectFieldIconsDisabled: '#a3a3a3',
    contentSelectFieldIconsError: '#a00000',
    strokeSelectField: '#c1c1c1',
    strokeSelectFieldHover: '#131313',
    strokeSelectFieldActive: '#131313',
    strokeSelectFieldError: '#a00000',
    shapeSelectField: '0px',
  },
  slider: {
    surfaceSliderValueIndicator: '#131313',
    contentSliderValueIndicator: '#ffffff',
    contentSlideLabels: '#636363',
    surfaceSliderTrackDot: '#a3a3a3',
    surfaceSliderInactiveTrack: '#dedede',
    surfaceSliderActiveTrack: '#000000',
    surfaceSliderDisabledTrack: '#838383',
    surfaceSliderControlDefault: '#ffffff',
    surfaceSliderControlHover: '#ffffff',
    surfaceSliderControlPressed: '#ffffff',
    surfaceSliderControlDisabled: '#fafafa',
    surfaceSliderControlAreaHover: '#00677f33',
    surfaceSliderControlAreaPressed: '#00677f66',
    shapeSlider: '8px',
  },
  stepper: {
    strokeStepperDefault: '#c1c1c1',
    strokeStepperActive: '#131313',
    default: {
      surfaceStepperActiveDefault: '#dedede',
      surfaceStepperCompletedDefault: '#000000',
      contentStepperIndicatorDefault: '#000000',
      contentStepperIndicatorDefaultContrast: '#ffffff',
      contentStepperLabelDefault: '#131313',
      contentStepperDescriptionDefault: '#292929',
    },
    disabled: {
      contentStepperDisabledIndicator: '#a3a3a3',
      contentStepperDisabledLabel: '#a3a3a3',
      contentStepperDisabledDescription: '#a3a3a3',
      strokeStepperDisabled: '#c1c1c1',
    },
    warning: {
      surfaceStepperWarning: '#e69123',
      contentStepperWarningIndicator: '#ffffff',
      contentStepperWarningLabel: '#131313',
      contentStepperWarningDescription: '#292929',
    },
    error: {
      surfaceStepperError: '#a00000',
      contentStepperErrorIndicator: '#ffffff',
      contentStepperErrorLabel: '#a00000',
      contentStepperErrorDescription: '#a00000',
    },
  },
  skeleton: {
    surfaceSkeletonStep1: '#f3f3f5',
    surfaceSkeletonStep2: '#dedede',
    shapeSkeleton: '0px',
  },
  tab: {
    default: {
      surfaceTab: '#ffffff00',
      surfaceTabActive: '#ffffff',
      surfaceTabHover: '#cce3eb',
      contentTabEnabled: '#00677f',
      contentTabHover: '#00677f',
      contentTabActive: '#00677f',
      contentTabDisabled: '#a3a3a3',
      strokeTabEnabled: '#dedede',
      strokeTabHover: '#dedede',
      strokeTabActive: '#00677f',
      strokeTabDisabled: '#dedede',
      shapeTab: '0px',
    },
    contained: {
      surfaceTab: '#ffffff00',
      surfaceTabActive: '#ffffff',
      surfaceTabHover: '#cce3eb',
      contentTabEnabled: '#00677f',
      contentTabHover: '#00677f',
      contentTabActive: '#00677f',
      contentTabDisabled: '#a3a3a3',
      shapeTab: '0px',
    },
  },
  tag: {
    solid: {
      squared: {
        surfaceTagSolidSquaredDefault: '#00677f',
        surfaceTagSolidSquaredHover: '#003041',
        surfaceTagSolidSquaredDisabled: '#cce3eb',
        contentTagSolidSquaredDefault: '#ffffff',
        contentTagSolidSquaredHover: '#ffffff',
        contentTagSolidSquaredDisabled: '#ffffff',
        shapeTagSolidSquared: '0px',
      },
      rounded: {
        surfaceTagSolidRoundedDefault: '#00677f',
        surfaceTagSolidRoundedHover: '#003041',
        surfaceTagSolidRoundedDisabled: '#cce3eb',
        contentTagSolidRoundedDefault: '#ffffff',
        contentTagSolidRoundedHover: '#ffffff',
        contentTagSolidRoundedDisabled: '#ffffff',
        shapeTagSolid: '16px',
      },
    },
    outlined: {
      squared: {
        surfaceTagOutlinedSquaredDefault: '#cce3eb',
        surfaceTagOutlinedSquaredHover: '#73aec2',
        surfaceTagOutlinedSquaredDisabled: '#cce3eb',
        contentTagOutlinedSquaredDefault: '#00677f',
        contentTagOutlinedSquaredHover: '#003041',
        contentTagOutlinedSquaredDisabled: '#73aec2',
        tagOutlinedSquaredStrokeDefault: '#00677f',
        strokeTagOutlinedSquaredHover: '#003041',
        strokeTagOutlinedSquaredDisabled: '#73aec2',
        shapeTagOutlinedSquared: '0px',
      },
      rounded: {
        surfaceTagOutlinedRoundedDefault: '#cce3eb',
        surfaceTagOutlinedRoundedHover: '#73aec2',
        surfaceTagOutlinedRoundedDisabled: '#cce3eb',
        contentTagOutlinedRoundedDefault: '#00677f',
        contentTagOutlinedRoundedHover: '#003041',
        contentTagOutlinedRoundedDisabled: '#73aec2',
        strokeTagOutlinedRoundedDefault: '#00677f',
        strokeTagOutlinedRoundedHover: '#003041',
        strokeTagOutlinedRoundedDisabled: '#73aec2',
        shapeTagOutlinedRounded: '16px',
      },
    },
  },
  table: {
    surfaceTableHeader: '#ffffff',
    surfaceTableBodyDefault: '#ffffff',
    surfaceTableBodyHover: '#fafafa',
    surfaceTableBodySelected: '#dedede',
    contentTableHeader: '#292929',
    contentTableDefault: '#292929',
    contentTableHover: '#131313',
    contentTableActive: '#131313',
    strokeTable: '#dedede',
  },
  textField: {
    surfaceTextFieldDefault: '#f3f3f5',
    surfaceTextFieldLight: '#fafafa',
    surfaceTextFieldContrast: '#ffffff',
    contentTextFieldLabel: '#292929',
    contentTextFieldLabelReadOnly: '#636363',
    contentTextFieldLabelError: '#a00000',
    contentTextFieldLabelDisabled: '#a3a3a3',
    contentTextFieldLabelFloating: '#636363',
    contentTextFieldLabelFloatingError: '#a00000',
    contentTextFieldLabelFloatingDisabled: '#a3a3a3',
    contentTextFieldPlaceholder: '#636363',
    contentTextFieldPlaceholderDisabled: '#a3a3a3',
    contentTextFieldText: '#292929',
    contentTextFieldTextReadOnly: '#636363',
    contentTextFieldTextDisabled: '#a3a3a3',
    contentTextFieldInfo: '#636363',
    contentTextFieldInfoError: '#a00000',
    contentTextFieldInfoDisabled: '#a3a3a3',
    contentTextFieldMandatory: '#a00000',
    contentTextFieldMandatoryDisabled: '#a3a3a3',
    contentTextFieldIcons: '#292929',
    contentTextFieldIconsReadOnly: '#636363',
    contentTextFieldIconsError: '#a00000',
    contentTextFieldIconsDisabled: '#a3a3a3',
    strokeTextField: '#c1c1c1',
    strokeTextFieldHover: '#131313',
    strokeTextFieldError: '#a00000',
    strokeTextFieldActive: '#131313',
    shapeTextField: '0px',
  },
  textarea: {
    surfaceTextareaDefault: '#f3f3f5',
    surfaceTextareaLight: '#fafafa',
    surfaceTextareaContrast: '#ffffff',
    contentTextareaLabel: '#292929',
    contentTextareaLabelReadOnly: '#636363',
    contentTextareaLabelError: '#a00000',
    contentTextareaLabelDisabled: '#a3a3a3',
    contentTextareaLabelFloating: '#636363',
    contentTextareaLabelFloatingError: '#a00000',
    contentTextareaLabelFloatingDisabled: '#a3a3a3',
    contentTextareaPlaceholder: '#636363',
    contentTextareaPlaceholderDisabled: '#a3a3a3',
    contentTextareaText: '#292929',
    contentTextareaTextReadOnly: '#636363',
    contentTextareaTextDisabled: '#a3a3a3',
    contentTextareaInfo: '#636363',
    contentTextareaInfoError: '#a00000',
    contentTextareaInfoDisabled: '#a3a3a3',
    contentTextareaCounter: '#636363',
    contentTextareaCounterError: '#a00000',
    contentTextareaCounterDisabled: '#a3a3a3',
    contentTextareaMandatory: '#a00000',
    contentTextareaMandatoryDisabled: '#a3a3a3',
    contentTextareaIcons: '#292929',
    contentTextareaIconsReadOnly: '#636363',
    contentTextareaIconsError: '#a00000',
    contentTextareaIconsDisabled: '#a3a3a3',
    strokeTextarea: '#c1c1c1',
    strokeTextareaHover: '#131313',
    strokeTextareaError: '#a00000',
    strokeTextareaActive: '#131313',
    shapeTextarea: '0px',
  },
  timepicker: {
    surfaceTimepickerDefault: '#ffffff',
    surfaceTimepickerHover: '#cce3eb',
    contentTimepicker: '#292929',
    contentTimepickerDisabled: '#a3a3a3',
    shapeTimepicker: '0px',
  },
  toastMessages: {
    success: {
      surfaceToastMessagesSuccess: '#ffffff',
      surfaceToastMessagesSuccessAccent: '#6ea046',
      contentToastMessagesSuccessTmIcon: '#ffffff',
      contentToastMessagesSuccessTitle: '#131313',
      contentToastMessagesSuccessDescription: '#292929',
      contentToastMessagesSuccessCloseIcon: '#292929',
      contentToastMessagesSuccessActions: '#454545',
      shapeToastMessagesSuccess: '0px',
    },
    error: {
      surfaceToastMessagesError: '#ffffff',
      surfaceToastMessagesErrorAccent: '#a00000',
      contentToastMessagesErrorTmIcon: '#ffffff',
      contentToastMessagesErrorTitle: '#131313',
      contentToastMessagesErrorDescription: '#292929',
      contentToastMessagesErrorCloseIcon: '#292929',
      contentToastMessagesErrorActions: '#454545',
      shapeToastMessagesError: '0px',
    },
    warning: {
      surfaceToastMessagesWarning: '#ffffff',
      surfaceToastMessagesWarningAccent: '#e69123',
      contentToastMessagesWarningTmIcon: '#ffffff',
      contentToastMessagesWarningTitle: '#131313',
      contentToastMessagesWarningDescription: '#292929',
      contentToastMessagesWarningCloseIcon: '#292929',
      contentToastMessagesWarningActions: '#454545',
      shapeToastMessagesWarning: '0px',
    },
    info: {
      surfaceToastMessagesInfo: '#ffffff',
      surfaceToastMessagesInfoAccent: '#008dfc',
      contentToastMessagesInfoTmIcon: '#ffffff',
      contentToastMessagesInfoTitle: '#131313',
      contentToastMessagesInfoDescription: '#292929',
      contentToastMessagesInfoCloseIcon: '#292929',
      contentToastMessagesInfoActions: '#454545',
      shapeToastMessagesInfo: '0px',
    },
  },
  toggle: {
    contentToggleDefault: '#292929',
    contentToggleContrast: '#ffffff',
    contentToggleDisabled: '#a3a3a3',
    shapeToggle: '56px',
    checkedTrue: {
      surfaceToggleCheckedEnabled: '#00677f',
      surfaceToggleCheckedDisabled: '#cce3eb',
    },
    checkedFalse: {
      surfaceToggleUncheckedDefault: '#dedede',
      surfaceToggleUncheckedDisabled: '#f3f3f5',
    },
  },
  tooltip: {
    surfaceTooltipDefault: '#131313',
    surfaceTooltipOpacity: '#131313b8',
    contentTooltipDefault: '#ffffff',
    shapeTooltip: '0px',
  },
};
