name: Continous Integration

env:
  TBLX_NPM_ARTIFACT_TOKEN: ${{ secrets.TBLX_NPM_ARTIFACT_TOKEN }}
  TBLX_NPM_ARTIFACT_USERNAME: ${{ secrets.TBLX_NPM_ARTIFACT_USERNAME }}

on:
  push:
    branches:
      - main
    paths:
      - "packages/dt-ui-react/**"
      - "apps/docs/**"

  pull_request:
    paths:
      - "packages/dt-ui-react/**"
      - "apps/docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node and yarn
        uses: "./.github/actions/yarn-node-install"
        with:
          CACHE_FILE_NAME: "global"
          TBLX_NPM_ARTIFACT_TOKEN: $TBLX_NPM_ARTIFACT_TOKEN
          TBLX_NPM_ARTIFACT_USERNAME: $TBLX_NPM_ARTIFACT_USERNAME

      - name: Run Lint
        run: yarn lint

  tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node and yarn
        uses: "./.github/actions/yarn-node-install"
        with:
          CACHE_FILE_NAME: "global"
          TBLX_NPM_ARTIFACT_TOKEN: $TBLX_NPM_ARTIFACT_TOKEN
          TBLX_NPM_ARTIFACT_USERNAME: $TBLX_NPM_ARTIFACT_USERNAME

      - name: Run Tests
        run: yarn test

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node and yarn
        uses: "./.github/actions/yarn-node-install"
        with:
          CACHE_FILE_NAME: "global"
          TBLX_NPM_ARTIFACT_TOKEN: $TBLX_NPM_ARTIFACT_TOKEN
          TBLX_NPM_ARTIFACT_USERNAME: $TBLX_NPM_ARTIFACT_USERNAME

      - name: Run Build
        run: yarn run turbo build --filter='./packages/*'
