name: Publish

env:
  TBLX_NPM_ARTIFACT_TOKEN: ${{ secrets.TBLX_NPM_ARTIFACT_TOKEN }}
  TBLX_NPM_ARTIFACT_USERNAME: ${{ secrets.TBLX_NPM_ARTIFACT_USERNAME }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  gather-changed-packages:
    if: "contains(github.event.head_commit.message, 'release:') || github.event_name == 'workflow_dispatch'"
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.filter-unpublished-packages.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 2

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install yarn and turbo
        shell: bash
        run: |
          npm install -g yarn
          npm install turbo@^2.0.6 --global

      - name: Get changed packages
        id: get-changed-packages
        run: |
          if [[ "${{ github.event_name }}" != 'workflow_dispatch' ]]; then
            TURBO_TELEMETRY_MESSAGE_DISABLED=1 npx -y turbo build --dry-run=json --filter=[..HEAD^1] --filter='!./apps/*' > $RUNNER_TEMP/turbo_result.json
          else
            TURBO_TELEMETRY_MESSAGE_DISABLED=1 npx -y turbo build --dry-run=json --filter='!./apps/*' > $RUNNER_TEMP/turbo_result.json
          fi

          echo "Turbo build output saved to $RUNNER_TEMP/turbo_result.json"

      - name: Filter unpublished packages
        id: filter-unpublished-packages
        run: |
          touch .npmrc
          echo "@dt-ui:registry=https://art.t3.daimlertruck.com/artifactory/api/npm/DTUI_NPM_LOCAL/" >> .npmrc
          echo "//art.t3.daimlertruck.com/artifactory/api/npm/DTUI_NPM_LOCAL/:always-auth=true" >> .npmrc
          echo "//art.t3.daimlertruck.com/artifactory/api/npm/DTUI_NPM_LOCAL/:_authToken=${TBLX_NPM_ARTIFACT_TOKEN}" >> .npmrc
          echo "//art.t3.daimlertruck.com/artifactory/api/npm/DTUI_NPM_LOCAL/:username=${TBLX_NPM_ARTIFACT_USERNAME}" >> .npmrc

          TURBO_RESULT=$(cat $RUNNER_TEMP/turbo_result.json)

          packages=$(echo "$TURBO_RESULT" | jq -r '.packages[]')

          unpublished_packages=()

          workspace_info=$(yarn workspaces --json info)
          parsed_workspace_info=$(echo "$workspace_info" | jq -r '.data | fromjson')

          for package in $packages; do
            echo "Checking package: $package"
            directory=$(echo "$parsed_workspace_info" | jq -r --arg package "$package" '.[$package].location')
            
            # Debug: directory
            echo "Directory for $package: $directory"
            
            if [[ ! -d "$directory" ]]; then
              echo "Directory does not exist for package $package: $directory"
              continue
            fi

            current_version=$(jq -r '.version' < "$directory/package.json")

            if [[ "$current_version" == "0.0.0" ]]; then
              echo "Skipping $package as its version is 0.0.0"
              continue
            fi

            published_versions=$(yarn info "$package" versions || echo "[]")

            if [[ $published_versions != *"$current_version"* ]]; then
              unpublished_packages+=("$package")
            fi
          done

          if [ ${#unpublished_packages[@]} -eq 0 ]; then
            echo "No unpublished packages."
            echo "result=[]" >> $GITHUB_OUTPUT
          else
            echo "Unpublished packages: ${unpublished_packages[@]}"
            result=$(printf '%s\n' "${unpublished_packages[@]}" | jq -R . | jq -s .)
            echo "result<<EOF" >> $GITHUB_OUTPUT
            echo "$result" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

  publish:
    runs-on: self-hosted
    needs: [gather-changed-packages]
    strategy:
      matrix:
        packages: ${{ fromJson(needs.gather-changed-packages.outputs.matrix) }}
        exclude:
          - packages: '//'
          - packages: '@dt-ui/docs'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup node and yarn
        uses: './.github/actions/yarn-node-install'
        with:
          CACHE_FILE_NAME: ${{ matrix.packages }}
          TBLX_NPM_ARTIFACT_TOKEN: $TBLX_NPM_ARTIFACT_TOKEN
          TBLX_NPM_ARTIFACT_USERNAME: $TBLX_NPM_ARTIFACT_USERNAME

      - name: Set package directory and version
        id: package-detail
        run: |
          directory=$(yarn workspaces --json info | jq -r '.data' | jq -r '.["${{ matrix.packages }}"].location')
          current_version=$(cat $directory/package.json | jq -r '.version')
          echo "directory=$directory" >> $GITHUB_OUTPUT
          echo "version=$current_version" >> $GITHUB_OUTPUT

      - name: Run build ${{ matrix.packages }}
        run: |
          yarn run turbo build --filter=${{ matrix.packages }}...

      - name: Yarn pack ${{ matrix.packages }}
        run: |
          yarn pack
        working-directory: ${{ steps.package-detail.outputs.directory }}

      - uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_USER: ${{ secrets.TBLX_NPM_ARTIFACT_USERNAME }}
          JF_PASSWORD: ${{ secrets.TBLX_NPM_ARTIFACT_PASSWORD }}

      - name: Publish to Artifactory
        run: jf rt u ${{ steps.package-detail.outputs.directory }}/*.tgz DTUI_NPM_LOCAL/${{ matrix.packages }}/-/ --flat=true
